##
## Bolt Auth configuration options
##
## Documentation:
##   * See the doc/ directory in this repository
##   * Online https://github.com/BoltAuth/Auth/tree/master/doc

## Debugging ##################################################################
#
debug: false

## Registration ###############################################################
#
registration:
    enabled: true

## Notification email addresses ###############################################
#
# Enable notifications and set a working email address.
# This is required for outgoing email to work on some servers
#
#notification:
#    name: Site Admin              # Display name used as the sender name
#    email: no-reply@example.com   # Email address as the sender address

## Access Control #############################################################
#
roles:
    auth:
        Tutor: Tutor
    #register:
        #Tutor: Tutor

## Authentication & OAuth2 Providers ##########################################
#
providers:
    local:
        label:
            sign_in: Sign in with an email address
            associate: --not applicable--
        enabled: true
        keys:
            client_id: localdefault
            client_secret: localdefault
        scopes: [ user ]

## Form Configuration #########################################################
#
forms:
    labels:
        login: Login
        logout: Logout
        displayname: ' '
        email: ' '
        password_first: ' '
        password_second: ' '
        profile_save: Save & Continue
    placeholders:
        displayname: Name
        email: Email
        password_first: Password
        password_second: Repeat Password            

        
redirects:
    login:  /
    logout: /
    
  

    
#urls:
#    authenticate: authentication
#    auth: auth
