extends:
###
### Bolt Forms
###

## Debugging
#
# Global debugging on/off switch
#
# If enabled, ALL forms will go into debug mode.
# NOTE: setting the debug on a specific form will override these global settings
# — specific for and to that form. It is considered best practice to use only
# this global setting.
debug:
    enabled: false
    address: noreply@example.com

## CSRF protection
#
# Enable CSRF protection for forms. You should leave this set to 'true', unless
# you know what you're doing.
csrf: true

# Global templates used for rendering forms and emails.
#
# You can find assorted templates to copy and modify in the templates/
# directory. Simply copy them to a directory of your choosing in your theme
# and set the template you want to override.
#
# More information on available template overrides can be found in the
# Templates section of docs.
#
# NOTE: All paths are relative of your running theme.
#
# e.g. You created your templates in the `extensions/boltforms/` directory
# inside your theme, you would use similar to:
#
#templates:
#    form: extensions/boltforms/form.twig
#    email: extensions/boltforms/email.twig
#    subject: extensions/boltforms/subject.twig
#    files: extensions/boltforms/file_browser.twig

## reCAPTCHa set up
#
# NOTE: You can get your keys from https://www.google.com/recaptcha/admin
# * `public_key` key will be labeled "Site key"
# * `private_key` key will be labeled "Secret key"
#
#recaptcha:
#    enabled: false
#    label: "Please enter the reCaptcha text to prove you're a human"
#    public_key: ''
#    private_key: ''
#    error_message: "The CAPTCHA wasn't entered correctly. Please try again."
#    theme: clean

## File Uploads
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SECURITY WARNING ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Handling file uploads is a very common attack vector used to compromise (hack)
# a server.
#
# BoltForms does a few things to help increase slightly the security of handling
# file uploads.
#
# Firstly, the directory that you specify for "base_directory" below should NOT
# be an route accessible to the outside world. We provide a special route should
# you wish to make the files browsable after upload.
#
# Secondly, is the "filename_handling" parameter. If an attacker knows the
# uploaded file name, this can make their job a bit easier. So we provide three
# options, e.g. uploading the file kitten.jpg:
#
# -------------------------------------
# | Setting | Resulting file name     |
# |-----------------------------------|
# | prefix  | kitten.Ze1d352rrI3p.jpg |
# | suffix  | kitten.jpg.Ze1d352rrI3p |
# | keep    | kitten.jpg              |
# -------------------------------------
#
# We recommend "suffix" as this is the most secure, alternatively "prefix" will
# aid in file browsing. However "keep" should always be used with caution!
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SECURITY WARNING ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
uploads:
    enabled: true                                 # The global on/off switch for upload handling
    base_directory: files/2018-06/             # Outside web root and writable by the web server's user
    filename_handling: keep                      # Can be either "prefix", "suffix", or "keep"
    management_controller: true                  # Enable a controller to handle browsing and downloading of uploaded files

                    
create_tutorial:
    submission:
        ajax: false   
    notification:
        enable: true
        debug: false
    feedback:
        success: succeded
        error: there was an error
        redirect:
            target: /page/create_entries
    database:
        contenttype: 
            name: tutorials     #define the table in the database where to write in
            #table: bolt_tutorials
        field_map:              #define the colunm of the selected table, where to put in the values
            title: 'title'
            teaser: 'teaser'
            body: 'body'
            image: 'image'
            guid: 'guid'
        fields:
            image:
                type: image
    templates:
        form: /boltforms/templates/form/form.twig     #path to the used template      
    fields:                                 # from this point define the type and the requirement of the fields in the table
        title:
            type: text
            options:
                required: true
        image:
            type: file
            options:
                required: false
        teaser:
            type: textarea
            options:
                required: true
        body:
            type: textarea
            options:
                required: true
        guid:
            type: hidden
            options:
                label: false
                attr:
                    value: guid
        status:
             type: hidden
             options:
                label: false
                attr:
                    value: published
        submit:                                 #defination of the submit button
            type: submit
            options:
                label: create tutorial »
                attr:
                    class: btn btn-light
                    style: padding-left:11px;margin-left:0px;margin-right:15px;

create_entries:
    submission:
        ajax: false
    notification:
        enable: true
        debug: false
    feedback:
        success: succeded
        error: there was an error
        redirect:
            target: /page/relation_entry_tutorial
    database:
        contenttype:
            name: entries
        field_map:
            title: 'title'
            body: 'body'
            image: 'image'
            video: 'video'
            tutorialid: 'tutorialid'
        fields:
            image:                              # casting the type file into the image or video type
                type: image
            video:
                type: video
    templates:
        form: /boltforms/templates/form/form.twig
    fields:
        title:
            type: text
        body:
            type: textarea
            options:
                required: true
        image:
            type: file
            options:
                required: false
                multiple: false
        video:
            type: file
            options:
                required: false
                multiple: true
                
        tutorialid:
            type: choice
            options: 
                required: true
                label: Entry related to which Tutorial
                choices: content
                params:
                    contenttype: tutorials
                    label: title
                    value: id
        status:
            type: hidden
            options:
                label: false
                attr:
                    value: published
        submit:
            type: submit    
            options:
                label: create Entry »
                attr:
                    class: btn btn-light
                    style: padding-left:11px;margin-left:0px;margin-right:15px;

relation:
    notification:
        enable: true
        debug: false
    feedback:
        success: succeded
        error: there was an error
        redirect:
            target: /page/create_entries
    database:
        table: bolt_relations
        field_map:
            from_contenttype: 'from_contenttype'
            from_id: 'from_id'
            to_contenttype: 'to_contenttype'
            to_id: 'to_id'
    templates:
        form: /boltforms/templates/form/form.twig
        
    fields:
        from_contenttype:
            type: hidden
            options:
                label: false
                attr:
                    value: entries
                
                   
        from_id:
            type: choice
            options:
                required: true
                label: entry selection
                choices: content
                params:
                    contenttype: entries
                    label: title
                    value: id
                      
        to_contenttype:
            type: hidden
            options:
                label: false
                attr:
                    value: tutorials
                
                       
        to_id:
            type: choice
            options:
                required: true
                label: Tutorial selection
                choices: content
                params:
                    contenttype: tutorials
                    label: title
                    value: id
        submit:
            type: submit    
            options:
                label: create relation »
                attr:
                    class: btn btn-light
                    style: padding-left:11px;margin-left:0px;margin-right:15px;

create_quiz:
    feedback:
        success: succeded
        error: there was an error
        redirect:
            target: /page/relation_quiz
    database:
        contenttype:
            name: create_quizes
        field_map:
            question: 'question'
            answer1: 'answer1'
            answer2: 'answer2'
            answer3: 'answer3'
            answer4: 'answer4'
            correct_answer: 'correct_answer'
            tutorialid: 'tutorialid'
    templates:
        form: /boltforms/templates/form/form.twig

    fields:
        question:
            type: text
            options:
                required: true
                label: Question
        answer1:
            type: text
            options:
                required: true
                label: Answer1
        answer2:
            type: text
            options:
                required: true
                label: Answer2
        answer3:
            type: text
            options:
                required: true
                label: Answer3
        answer4:
            type: text
            options:
                required: true
                label: Answer4
        correct_answer:
            type: choice
            options:
                required: true  
                expanded: true
                multiple: false
                choices: {'Answer1':'answer1','Answer2':'answer2','Answer3':'answer3','Answer4':'answer4'}
        tutorialid:
            type: choice
            options: 
                required: true
                label: question related to which Tutorial
                choices: content
                params:
                    contenttype: tutorials
                    label: title
                    value: id
        submit:
            type: submit    
            options:
                label: create relation »
                attr:
                    class: btn btn-light
                    style: padding-left:11px;margin-left:0px;margin-right:15px;

                    
relation_quiz_tutorial:
    notification:
        enable: true
        debug: false
    feedback:
        success: succeded
        error: there was an error
        redirect:
            target: /page/create_quiz
    database:
        table: bolt_relations
        field_map:
            from_contenttype: 'from_contenttype'
            from_id: 'from_id'
            to_contenttype: 'to_contenttype'
            to_id: 'to_id'
    templates:
        form: /boltforms/templates/form/form.twig
        
    fields:
        from_contenttype:
            type: hidden
            options:
                label: false
                attr:
                    value: create_quizes
                
                   
        from_id:
            type: choice
            options:
                required: true
                label: Quiz selection
                choices: content
                params:
                    contenttype: create_quizes
                    label: question
                    value: id
                      
        to_contenttype:
            type: hidden
            options:
                label: false
                attr:
                    value: tutorials
                
                       
        to_id:
            type: choice
            options:
                required: true
                label: Tutorial selection
                choices: content
                params:
                    contenttype: tutorials
                    label: title
                    value: id
        submit:
            type: submit    
            options:
                label: create relation »
                attr:
                    class: btn btn-light
                    style: padding-left:11px;margin-left:0px;margin-right:15px;


abo:
    database:
        contenttype:
            name: abo
        fils_map:
            guid: 'guid'
            tutorialid: 'tutorialid'
    templates:
        form: /boltforms/templates/form/form.twig

    fields:
        guid:
            type: hidden
            options:
                label: false
                attr:
                    value: guid
        tutorialid:
            type: hidden
            options:
                label: false
                attr:
                    value: tid
        submit:
            type: submit    
            options:
                label: subscribe 
                attr:
                    class: btn btn-light
                    style: padding-left:11px;margin-left:0px;margin-right:15px;
quiz-answer:
    database:
        contenttype:
            name: q_answers
        field_map:
            usrname: 'usrname'
            slugquiz: 'slugquiz'
            answer: 'answer'
    templates:
        form: /boltforms/templates/form/form.twig
    fields:
        usrname:
            type: hidden
            options:
                label: false
                attr:
                    value: name
        slugquiz:
            type: hidden
            options:
                label: false
                attr:
                    value: slug1
        answer:
            type: choice
            options:
                expanded: true
                multiple: false
                choices: {'Answer1':'answer1','Answer2':'answer2','Answer3':'answer3','Answer4':'answer4'}
        submit:
            type: submit    
            options:
                label: submit
                attr:
                    class: btn btn-light
                    style: padding-left:11px;margin-left:0px;margin-right:15px;

upload_page:
    templates:    
        form: /boltforms/templates/form/form.twig
    submission:
        ajax: false
    notification:
        enable: true
        debug: false
    feedback:
        success: succeded
        error: there was an error
        redirect:
            target: /page/relation_entry_tutorial
    database:
        contenttype:
            name: upload
        field_map:
            pdf: 'pdf'
            tutorialid: 'tutorialid'
    fields:
        pdf:
            type: file
            options:
                label: 'File-Upload'
                required: false
                multiple: true
        tutorialid:
            type: choice
            options:
                required: true
                label: Tutorial selection
                choices: content
                params:
                    contenttype: tutorials
                    label: title
                    value: id
        status:
            type: hidden
            options:
                label: false
                attr:
                    value: published
        submit:
            type: submit    
            options:
                label: Upload File
                attr:
                    class: btn btn-light
                    style: padding-left:11px;margin-left:0px;margin-right:15px;
