# set CDN url if its set and the config option of "use_cdn" is true then use this path for the video




# breakdown of options available to use:
# * use_cdn: [true | false ] this defaults to false
# * video_id: gives the containing element an ID as a hook for styling :( or JavaScript :) you should set this in your template if you plan to use this config group multiple times.
# * class: CSS class
# * attributes: [ 'autoplay', 'controls', 'muted', 'loop', 'playsinline' ] # dont use autplay please :)
# * preload: 'metadata' # options are metadata | auto | none
# * width_height: [ 400, 400 ] # the width and height of the video element if you have one... optional
# * media_fragment: [ start_time, end_time ] to play a specific portion of the video see: http://www.html5rocks.com/en/tutorials/video/basics/#toc-markup


# ================================================================================= #
# Full Example
# ================================================================================= #
#default:
#  use_cdn: true
#  video_id: blogVideo
#  class: ['class-one']
#  attributes: [ 'autoplay', 'controls', 'muted', 'loop' ]
#  preload: 'metadata'
#  width_height: [ 400, 400 ]
#  media_fragment: [10, 60 ]

#default:
#  use_cdn: false
#  attributes: [ 'controls']
#  preload: 'metadata'

default:
    use_cdn: false
    attributes: [ 'controls']
    preload: 'metadata'

# --------------------------------------------------------------------------------- #
# Example of using a video as a gif-like animation.
# 1. Controls are added so a person can stop and start - not needed but "nice to have"
# 2. Autoplay, muted  are set so mobile devices will automatically play the video - chrome 52+ iOs 10+
# 3. loop is set to loop the video like a gif
# 4. playsinline is set so it plays within the page for iOs instead of fullscreen see: https://webkit.org/blog/6784/new-video-policies-for-ios/
# --------------------------------------------------------------------------------- #

gifLike:
    attributes: [ 'controls', 'autoplay', 'muted', 'loop', 'playsinline' ]
    width_height: [ 400, '100%' ]

blogVideos:
    use_cdn: false
    video_poster: 'path/to/poster.png'
    attributes: [ 'controls', 'muted' ]
    preload: 'metadata'
    width_height: [ 600, 400 ]
    media_fragment: [ 0, 60 ]
#  multiple_source: true
 

#fullExample:
#  use_cdn: false
#  class: [ 'test-class' ]
#  video_id: 'testID'
#  video_poster: 'theme/base-2016/images/poster-test.svg' # if you want a poster image to load
#  attributes: [ 'controls']
#  preload: 'metadata'
#  width_height: [ 400, 400 ] # the width and height of the video element if you have one... optional
#  tracks:
#    en_subtitles:
##      kind: 'subtitles'
 #     srclang: 'en'
 #     label: 'English subtitles'
 #     src: '/theme/base-2016/file.vtt'
 #     default: true
#    es_subtitles:
##      kind: 'subtitles'
 #     srclang: 'es'
 #     label: 'Español subtitles'
 #     src: '/theme/base-2016/file-es.vtt'
 #   en_captions:
 ##     kind: 'captions'
  #    srclang: 'en'
  #    label: 'English Captions'
  #    src: '/theme/base-2016/captions.vtt'
